services:
  selenium-service:
    build: .

    image: ghcr.io/kyledurieux/selenium-service:latest
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    shm_size: "2gb"        # important for Chrome stability
    
    
    env_file:
      - ./app/.env

    environment:
      - TZ=America/Denver
      - API_TOKEN=${API_TOKEN}

    pull_policy: never

    volumes:
      - /home/ubuntu/selenium-service/jobs:/app/jobs
      - /home/ubuntu/selenium-service/app:/app
      - /home/ubuntu/cnh_runtime:/app/runtime


